name: Deploy Knative Service
description:
  Create or update a Knative Service without dealing with Kubernetes complexity
author: The Origami Corporation

branding:
  icon: cloud
  color: blue

# Define your inputs here.
inputs:
  service_name:
    description: 'Name of the Knative service to create or update'
    required: true

  image:
    description:
      'Container image to deploy (e.g., reg.rso.dev/my-project/image:tag)'
    required: true

  env_vars:
    description:
      'Environment variables in JSON format:
      [{"name":"VAR_NAME","value":"var_value"}]'
    required: false

  annotations:
    description:
      'Service annotations in JSON format:
      [{"key":"annotation.key","value":"annotation-value"}]'
    required: false

  labels:
    description:
      'Service labels in JSON format:
      [{"key":"label.key","value":"label-value"}]'
    required: false

  resource_limits_cpu:
    description: 'CPU resource limit (e.g., "500m")'
    required: false

  resource_limits_memory:
    description: 'Memory resource limit (e.g., "512Mi")'
    required: false

  resource_requests_cpu:
    description: 'CPU resource request (e.g., "100m")'
    required: false

  resource_requests_memory:
    description: 'Memory resource request (e.g., "128Mi")'
    required: false

  container_port:
    description: 'Container port to expose'
    required: false
    default: '8080'

  port_name:
    description: 'Name of the port (must be "h2c" or "http1" if specified)'
    required: false

  image_pull_secret_name:
    description: 'Image pull secret name'
    required: false
    default: 'regcred'

# Define your outputs here.
outputs:
  service_url:
    description: 'The URL of the deployed Knative service'

  revision_name:
    description: 'The name of the created revision'

runs:
  using: node20
  main: dist/index.js
